### ISSUE TITLE
Create click endpoint doesn't accept IPv6 addresses

### ISSUE THREAD

**Issue by damir-bajramovic** [Tapfiliate/tapfiliate-js#2]
Greetings, 

Not an issue with the library, but the API itself. 

The API doesn't accept valid IPv6 addresses in the request payload.

Steps to reproduce:
- Post request to: `https://api.tapfiliate.com/1.6/clicks`
- Put a valid IPv6 address to the request body, example: `2806:10be:a:95f2:7097:5202:aced:368f`
- Responds with status code `400` and the message: `Request failed with status code 400`

**Comment by 4overking** [comment]
Hi Damir, thanks for reaching out and reporting the issue.
We're sorry for the inconvenience. This is resolved, and should be up and running now!
Please, let us know how it works on your end now, or if there's anything else we could assist you with. We'll be happy to help.

**Comment by damir-bajramovic** [comment]
Worked well. Thanks for fixing it promptly.
