### ISSUE TITLE
Tapfiliate throwing errors in console due to incorrect usage of "this"

### ISSUE THREAD

**Issue by Cosmin-Hodor** [Tapfiliate/tapfiliate-js#4]
I have opened the following PR: https://github.com/Tapfiliate/tapfiliate-js/pull/3

Is there any chance we could push those changes anytime soon? The library throws off SEO metrics due to the fact that its throwing a bunch of errors in the console upon serving a built project.

**Comment by 4overking** [comment]
Can be merget only next week.
